/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/ForgotPasswordScreen` | `/ForgotPasswordScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignInScreen` | `/SignInScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignUpScreen` | `/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/concerts` | `/concerts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/library` | `/library`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/ForgotPasswordScreen` | `/ForgotPasswordScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/SignInScreen` | `/SignInScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/SignUpScreen` | `/SignUpScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/concerts` | `/concerts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/library` | `/library`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/ForgotPasswordScreen${`?${string}` | `#${string}` | ''}` | `/ForgotPasswordScreen${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/SignInScreen${`?${string}` | `#${string}` | ''}` | `/SignInScreen${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/SignUpScreen${`?${string}` | `#${string}` | ''}` | `/SignUpScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/concerts${`?${string}` | `#${string}` | ''}` | `/concerts${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/library${`?${string}` | `#${string}` | ''}` | `/library${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/ForgotPasswordScreen` | `/ForgotPasswordScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignInScreen` | `/SignInScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignUpScreen` | `/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/concerts` | `/concerts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/library` | `/library`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; };
    }
  }
}
